### ISSUE TITLE
Handling of SUSE Manager Clients RPMs

### ISSUE THREAD

**Issue by roseswe** [doccaz/scc-tools#29] opened 2022-12-09 08:26 UTC
I consider this more an enhancement than a bug.

Can you either 
- exclude RPMs that belong to the SUSE Manger Bootstrap repo or
- always fetch SUSE Manager repo on top

Some packages that vercheck claims to be "unsupported"  ;-)

sle-manager-tools-release | SUSE Linux Enterprise 12 | 12-10.3.1
sle-manager-tools-release-POOL | SUSE Linux Enterprise 12 | 12-1.20
python2-rhnlib | SUSE Linux Enterprise 12 | 4.3.4-21.43.3
spacewalk-usix | SUSE Linux Enterprise 12 | 4.0.9-3.6.7
supportutils-plugin-salt | SUSE Linux Enterprise 12 | 1.2.0-6.16.1

sle-manager-tools-release | SUSE Linux Enterprise 15 | 15-113.8.1

**Comment by doccaz** [comment] 2022-12-15 20:43
Sorry for the delay. The problem is that SCC itself does not list these packages in their database. 
I guess one solution is to list these as exceptions inside the code itself. I'll get a couple supportconfigs from SUMA machines and see if there is the package set is small enough to do this.

**Comment by roseswe** [comment] 2022-12-16 13:40
Maybe add a "blacklist" (text-file) with RPM filenames that vercheck shall ignore?

**Comment by doccaz** [comment] 2022-12-16 18:14
Would you happen to have an example supportconfig where that happens (or a case # where I could download it from)? Tried on 4 different supportconfigs from SUMA servers, did not get the unsupported entries you mentioned.

**Comment by doccaz** [comment] 2022-12-20 15:55
@roseswe , I got your CSV files, and I think I found the problem: most of the packages reported as "not found" are leftover files from SUSE Manager 3.2 (or even older). At the time, the SUSE Manager repositories were a "module" tied to SLES up to 12 SP4. Were these systems later upgraded to SP5? If so, these would indeed show up as "not found" as they are orphan packages now.

For example, the package 'spacewalk-usix' can still be found in 12 SP4 as a valid package: https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=12.4&arch=x86_64&query=spacewalk-usix&module=

whereas it's no longer present in 12 SP5 as a valid package: https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=12.5&arch=x86_64&query=spacewalk-usix&module=

There is also another class of packages that depends on which medium the installation came from, like "sles-release-DVD", which, as the name says, only comes from a machine installed via ISO, or the -POOL versions of it.

I believe the common thread here is that if we find packages in the "not found" list that have a vendor "SUSE Linux Enterprise" (with the exception of "sles-release-*"), it could mean that we have orphan packages from an older product. I could either a) print a warning at the end about them; or b) create new CSV called "orphans". 

What do you think would be the best approach?

**Comment by roseswe** [comment] 2022-12-20 16:03
I vote for the "orphans" approach :-)  Maybe "SUSE orphans"?

**Comment by doccaz** [comment] 2022-12-20 21:52
Done: b54406e and 9801a90

Could you test it, please? Also note that I'm making the -cache version the default one now.

**Comment by doccaz** [comment] 2022-12-23 13:44
Thanks for testing, I'll be closing this issue.

**Closed as completed by doccaz** 2022-12-23 13:44 UTC
Labels: enhancement
